# Generated by Django 4.1 on 2022-08-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='GetCourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountUserId', models.BigIntegerField(verbose_name='ID с GetCourse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин работника')),
            ],
            options={
                'verbose_name': 'Учитель GetCourse',
                'verbose_name_plural': 'Учителя GetCourse',
            },
        ),
        migrations.CreateModel(
            name='GetCourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('lessons', models.ManyToManyField(to='getcourse.lesson', verbose_name='Уроки')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='getcourse.getcourseteacher', verbose_name='Учитель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='getcourse.getcourseuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ученик GetCourse',
                'verbose_name_plural': 'Ученики GetCourse',
            },
        ),
    ]
