# Generated by Django 4.1 on 2022-08-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0003_getcoursestudent_hours_alter_getcoursestudent_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
