# Generated by Django 4.1 on 2022-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0004_rename_datetime_lesson_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcourseteacher',
            name='avaliable_lessons',
            field=models.ManyToManyField(blank=True, to='getcourse.lesson', verbose_name='Доступные уроки'),
        ),
    ]
