# Generated by Django 4.1 on 2022-08-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0006_rename_avaliable_lessons_getcourseteacher_available_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getcoursestudent',
            name='lessons',
        ),
        migrations.CreateModel(
            name='LessonBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время урока')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на встречу')),
                ('password', models.URLField(blank=True, null=True, verbose_name='Паролб встречи')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getcourse.getcoursestudent', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getcourse.getcourseteacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Урок забронированный',
                'verbose_name_plural': 'Уроки забронированные',
            },
        ),
    ]
