# Generated by Django 4.1 on 2022-08-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0008_alter_lessonbooked_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcourseteacher',
            name='zoom_key',
            field=models.CharField(default=' ', max_length=255, verbose_name='Ключ Zoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='getcourseteacher',
            name='zoom_sec',
            field=models.CharField(default=' ', max_length=255, verbose_name='Секретный ключ Zoom'),
            preserve_default=False,
        ),
    ]
