# Generated by Django 4.1 on 2022-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0009_getcourseteacher_zoom_key_getcourseteacher_zoom_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonbooked',
            old_name='password',
            new_name='zoom_password',
        ),
        migrations.RenameField(
            model_name='lessonbooked',
            old_name='url',
            new_name='zoom_url',
        ),
        migrations.AddField(
            model_name='getcourseteacher',
            name='zoom_email',
            field=models.EmailField(default=' ', max_length=254, verbose_name='Почта Zoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonbooked',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID встречи'),
        ),
    ]
