# Generated by Django 4.1 on 2022-08-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0010_rename_password_lessonbooked_zoom_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcourseteacher',
            name='photo',
            field=models.URLField(default='https://myyestoday.ru/public/img/default_profile_50.png', verbose_name='Фото профиля'),
        ),
    ]
