# Generated by Django 4.1 on 2022-08-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0011_getcourseteacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcoursestudent',
            name='telegram_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Salebot'),
        ),
        migrations.AlterField(
            model_name='getcoursestudent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getcourse.getcourseteacher', verbose_name='Учитель'),
        ),
    ]
