# Generated by Django 4.1.5 on 2023-01-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0012_getcoursestudent_telegram_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='src',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text_down',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст сверху'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text_up',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст сверху'),
        ),
        migrations.AlterField(
            model_name='getcoursestudent',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='getcoursestudent',
            name='surname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='getcoursestudent',
            name='telegram_client_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID Salebot'),
        ),
        migrations.AlterField(
            model_name='getcourseteacher',
            name='zoom_key',
            field=models.CharField(max_length=500, verbose_name='Ключ Zoom'),
        ),
        migrations.AlterField(
            model_name='getcourseteacher',
            name='zoom_sec',
            field=models.CharField(max_length=500, verbose_name='Секретный ключ Zoom'),
        ),
    ]
