# Generated by Django 4.1.5 on 2023-01-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0013_alter_audio_src_alter_audio_text_down_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.UUIDField(verbose_name='№ задания')),
                ('answer', models.JSONField(verbose_name='Овет')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getcourse.getcourseuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ ученика',
                'verbose_name_plural': 'Ответы учеников',
            },
        ),
    ]
