# Generated by Django 4.1.5 on 2023-01-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getcourse", "0014_answer"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="user",),
        migrations.AddField(
            model_name="answer",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="getcourse.getcourseuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.JSONField(verbose_name="Ответ"),
        ),
    ]
