# Generated by Django 4.1.5 on 2023-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getcourse", "0015_remove_answer_user_answer_users_alter_answer_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="users",
            field=models.ManyToManyField(
                blank=True, to="getcourse.getcourseuser", verbose_name="Пользователь"
            ),
        ),
    ]
