# Generated by Django 4.1.5 on 2023-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcourse', '0016_alter_answer_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getcourseteacher',
            name='accountUserId',
            field=models.BigIntegerField(unique=True, verbose_name='ID с GetCourse'),
        ),
        migrations.AlterField(
            model_name='getcourseuser',
            name='accountUserId',
            field=models.BigIntegerField(unique=True, verbose_name='ID с GetCourse'),
        ),
    ]
